/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * 我的博客 API
 * 基于 Go + GORM 的博客系统后端
 * OpenAPI spec version: 0.1
 */
import type { ModelType } from './modelType';
import type { UtilsJsonResult } from './utilsJsonResult';

export type GetTypeAll200 = UtilsJsonResult & {
  data?: ModelType[];
};
