/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * 我的博客 API
 * 基于 Go + GORM 的博客系统后端
 * OpenAPI spec version: 0.1
 */

export type GetTypeParams = {
/**
 * 当前页码 (默认1)
 */
current?: number;
/**
 * 每页条数 (默认10)
 */
size?: number;
};
