/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * 我的博客 API
 * 基于 Go + GORM 的博客系统后端
 * OpenAPI spec version: 0.1
 */

export interface ModelArticle {
  content?: string;
  createTime?: string;
  description?: string;
  /** 必须大写开头！后面反引号里的才是数据库真实的列名 */
  id?: number;
  title?: string;
  typeId?: string;
}
