/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * 我的博客 API
 * 基于 Go + GORM 的博客系统后端
 * OpenAPI spec version: 0.1
 */
import type { DatatypesJSONTypeModelAppContent } from './datatypesJSONTypeModelAppContent';

export interface ModelAppInfo {
  /** 使用 JSONType 绑定上面的结构体 */
  content?: DatatypesJSONTypeModelAppContent;
  id?: number;
  version?: string;
}
