/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * 我的博客 API
 * 基于 Go + GORM 的博客系统后端
 * OpenAPI spec version: 0.1
 */

export interface ModelComment {
  avatar?: string;
  blogUrl?: string;
  /** 子评论树：Java 端用 Map 动态塞进 children，这里直接显式声明
  GORM 在使用 Preload("Children") 时会自动按 reply_cm_id 关联回填 */
  children?: ModelComment[];
  content?: string;
  createTime?: string;
  email?: string;
  id?: number;
  nickName?: string;
  replyArticleId?: number;
  /** 父级评论 ID，使用指针以表达 NULL（即根评论） */
  replyCmId?: number;
}
