/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * 我的博客 API
 * 基于 Go + GORM 的博客系统后端
 * OpenAPI spec version: 0.1
 */

export interface UtilsJsonResult {
  /** 业务约定：0 为成功，-1 为失败 */
  code?: number;
  /** 业务数据 */
  data?: unknown;
  /** 错误描述或提示信息 */
  msg?: string;
}
