/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * 我的博客 API
 * 基于 Go + GORM 的博客系统后端
 * OpenAPI spec version: 0.1
 */
import type {
  DeleteComment200,
  DeleteCommentParams,
  GetComment200,
  GetCommentId200,
  GetCommentParams,
  ModelComment,
  PostComment200,
  PutComment200
} from '../model';

import { customAxiosInstance } from '../api.base';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  /**
 * 按文章 ID 分页获取根评论，子评论会通过 children 字段一起返回
 * @summary 获取评论列表
 */
export const getComment = (
    params: GetCommentParams,
 options?: SecondParameter<typeof customAxiosInstance<GetComment200>>,) => {
      return customAxiosInstance<GetComment200>(
      {url: `/comment`, method: 'GET',
        params
    },
      options);
    }
  /**
 * @summary 更新评论
 */
export const putComment = (
    modelComment: ModelComment,
 options?: SecondParameter<typeof customAxiosInstance<PutComment200>>,) => {
      return customAxiosInstance<PutComment200>(
      {url: `/comment`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: modelComment
    },
      options);
    }
  /**
 * 根评论不传 replyCmId；回复某条评论时传上对应的 replyCmId
 * @summary 新增评论
 */
export const postComment = (
    modelComment: ModelComment,
 options?: SecondParameter<typeof customAxiosInstance<PostComment200>>,) => {
      return customAxiosInstance<PostComment200>(
      {url: `/comment`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: modelComment
    },
      options);
    }
  /**
 * @summary 删除评论
 */
export const deleteComment = (
    params: DeleteCommentParams,
 options?: SecondParameter<typeof customAxiosInstance<DeleteComment200>>,) => {
      return customAxiosInstance<DeleteComment200>(
      {url: `/comment`, method: 'DELETE',
        params
    },
      options);
    }
  /**
 * @summary 获取评论详情
 */
export const getCommentId = (
    id: number,
 options?: SecondParameter<typeof customAxiosInstance<GetCommentId200>>,) => {
      return customAxiosInstance<GetCommentId200>(
      {url: `/comment/${id}`, method: 'GET'
    },
      options);
    }
  export type GetCommentResult = NonNullable<Awaited<ReturnType<typeof getComment>>>
export type PutCommentResult = NonNullable<Awaited<ReturnType<typeof putComment>>>
export type PostCommentResult = NonNullable<Awaited<ReturnType<typeof postComment>>>
export type DeleteCommentResult = NonNullable<Awaited<ReturnType<typeof deleteComment>>>
export type GetCommentIdResult = NonNullable<Awaited<ReturnType<typeof getCommentId>>>
