/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * 我的博客 API
 * 基于 Go + GORM 的博客系统后端
 * OpenAPI spec version: 0.1
 */
import type {
  DeleteMoodId200,
  GetMood200,
  GetMoodParams,
  ModelMood,
  PostMood200,
  PutMood200
} from '../model';

import { customAxiosInstance } from '../api.base';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  /**
 * @summary 获取心情列表
 */
export const getMood = (
    params?: GetMoodParams,
 options?: SecondParameter<typeof customAxiosInstance<GetMood200>>,) => {
      return customAxiosInstance<GetMood200>(
      {url: `/mood`, method: 'GET',
        params
    },
      options);
    }
  /**
 * @summary 修改心情
 */
export const putMood = (
    modelMood: ModelMood,
 options?: SecondParameter<typeof customAxiosInstance<PutMood200>>,) => {
      return customAxiosInstance<PutMood200>(
      {url: `/mood`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: modelMood
    },
      options);
    }
  /**
 * @summary 添加心情
 */
export const postMood = (
    modelMood: ModelMood,
 options?: SecondParameter<typeof customAxiosInstance<PostMood200>>,) => {
      return customAxiosInstance<PostMood200>(
      {url: `/mood`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: modelMood
    },
      options);
    }
  /**
 * @summary 删除心情
 */
export const deleteMoodId = (
    id: number,
 options?: SecondParameter<typeof customAxiosInstance<DeleteMoodId200>>,) => {
      return customAxiosInstance<DeleteMoodId200>(
      {url: `/mood/${id}`, method: 'DELETE'
    },
      options);
    }
  export type GetMoodResult = NonNullable<Awaited<ReturnType<typeof getMood>>>
export type PutMoodResult = NonNullable<Awaited<ReturnType<typeof putMood>>>
export type PostMoodResult = NonNullable<Awaited<ReturnType<typeof postMood>>>
export type DeleteMoodIdResult = NonNullable<Awaited<ReturnType<typeof deleteMoodId>>>
