/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * 我的博客 API
 * 基于 Go + GORM 的博客系统后端
 * OpenAPI spec version: 0.1
 */
import type {
  DeleteType200,
  DeleteTypeParams,
  GetType200,
  GetTypeAll200,
  GetTypeId200,
  GetTypeParams,
  ModelType,
  PostType200,
  PutType200
} from '../model';

import { customAxiosInstance } from '../api.base';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  /**
 * 分页获取文章分类
 * @summary 获取分类列表
 */
export const getType = (
    params?: GetTypeParams,
 options?: SecondParameter<typeof customAxiosInstance<GetType200>>,) => {
      return customAxiosInstance<GetType200>(
      {url: `/type`, method: 'GET',
        params
    },
      options);
    }
  /**
 * @summary 修改分类
 */
export const putType = (
    modelType: ModelType,
 options?: SecondParameter<typeof customAxiosInstance<PutType200>>,) => {
      return customAxiosInstance<PutType200>(
      {url: `/type`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: modelType
    },
      options);
    }
  /**
 * @summary 新增分类
 */
export const postType = (
    modelType: ModelType,
 options?: SecondParameter<typeof customAxiosInstance<PostType200>>,) => {
      return customAxiosInstance<PostType200>(
      {url: `/type`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: modelType
    },
      options);
    }
  /**
 * @summary 删除分类
 */
export const deleteType = (
    params: DeleteTypeParams,
 options?: SecondParameter<typeof customAxiosInstance<DeleteType200>>,) => {
      return customAxiosInstance<DeleteType200>(
      {url: `/type`, method: 'DELETE',
        params
    },
      options);
    }
  /**
 * 通常用于前端下拉框
 * @summary 获取全部分类
 */
export const getTypeAll = (

 options?: SecondParameter<typeof customAxiosInstance<GetTypeAll200>>,) => {
      return customAxiosInstance<GetTypeAll200>(
      {url: `/type/all`, method: 'GET'
    },
      options);
    }
  /**
 * @summary 获取分类详情
 */
export const getTypeId = (
    id: number,
 options?: SecondParameter<typeof customAxiosInstance<GetTypeId200>>,) => {
      return customAxiosInstance<GetTypeId200>(
      {url: `/type/${id}`, method: 'GET'
    },
      options);
    }
  export type GetTypeResult = NonNullable<Awaited<ReturnType<typeof getType>>>
export type PutTypeResult = NonNullable<Awaited<ReturnType<typeof putType>>>
export type PostTypeResult = NonNullable<Awaited<ReturnType<typeof postType>>>
export type DeleteTypeResult = NonNullable<Awaited<ReturnType<typeof deleteType>>>
export type GetTypeAllResult = NonNullable<Awaited<ReturnType<typeof getTypeAll>>>
export type GetTypeIdResult = NonNullable<Awaited<ReturnType<typeof getTypeId>>>
